apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dredge

resources:
  - namespace.yaml
  - configmap.yaml
  - redis.yaml
  - dredge-server.yaml
  - quasimoto-mcp.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: dredge-cli
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/queenfi703/dredge-cli
    newTag: latest-cpu
